### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by Chrisvossetje** [forestcaver/MIStagesStuff#1]
Hey,
Thanks for the awesome work!! Really thanks.(good english over there)

There is a small type on line 81 in settings.cc
The [2].adc_scale is not correctly set.

79 persistent_data_.channel_calibration_data[1].adc_scale = -1.0f /* FIXME */;
80 persistent_data_.channel_calibration_data[2].adc_offset = 0.0f /* FIXME */;
81 persistent_data_.channel_calibration_data[3].adc_scale = -1.0f /* FIXME */;
82 persistent_data_.channel_calibration_data[3].adc_offset = 0.0f /* FIXME */;

**Comment by forestcaver** [comment]
Thanks! Hadnt spotted that! It’s never used though - it’s all #if 0 ‘d out.... I’ll update it anyway though for clarity
