### ISSUE TITLE
Wrong array index in settings.cc

### ISSUE THREAD

**Issue by mcleinn** [forestcaver/MIStagesStuff#3]
Thank you for the stages calibration code, it helped me a lot!

I noticed a small issue in the default settings in settings.cc, which can be easily overlooked when someone overwrites the default entries with his/her calculated values- leading to wrong calibration. 

  persistent_data_.channel_calibration_data[3].adc_scale = -1.0f /* FIXME */;
  persistent_data_.channel_calibration_data[3].adc_offset = 0.0f /* FIXME */;
  persistent_data_.channel_calibration_data[3].adc_scale = -1.0f /* FIXME */;

The first index should be 2, not 3.

All the best!

**Comment by forestcaver** [comment]
Thanks - fixed - only just seen this ! Apologies for the delay.
