### ISSUE TITLE
Unstable calibration problem

### ISSUE THREAD

**Issue by frekkia** [forestcaver/MIStagesStuff#4]
When you tried to calibrate the voltage goes down very slowly, but goes down all the time, is this normal? should i mark the voltage anyway?

Thanks!

**Comment by forestcaver** [comment]
This is not an issue with the calibration routine to my knowledge.

**Comment by frekkia** [comment]
So the voltage must stay fixed? Could I have done something wrong?

**Comment by frekkia** [comment]
So it should stay fixed? Could I have done something wrong?

**Comment by forestcaver** [comment]
I’m sorry - I cant offer you build support on GitHub for your module. But you almost certainly have a build issue with your module.

**Comment by frekkia** [comment]
> module



> I’m sorry - I cant offer you build support on GitHub for your module. But you almost certainly have a build issue with your module.

Where can we talk? I am desperate :(

**Comment by forestcaver** [comment]
I’m sorry - I cant offer you build support. I’m sorry - I simply dont have the time to sort out your module for you.
